-- MySQL Script generated by MySQL Workbench
-- Sun Mar 15 18:08:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema seguimiento_compras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seguimiento_compras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seguimiento_compras` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `seguimiento_compras` ;

-- -----------------------------------------------------
-- Table `seguimiento_compras`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_compras`.`proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_compras`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_compras`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proveedor_id` INT NOT NULL,
  `fecha_entrega_provable` DATE NULL DEFAULT NULL,
  `gerente` VARCHAR(100) NULL DEFAULT NULL,
  `estado` ENUM('PENDIENTE', 'RECIBIDO', 'NOVEDAD') NULL DEFAULT 'PENDIENTE',
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `proveedor_id` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `compras_ibfk_1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `seguimiento_compras`.`proveedores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_compras`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_compras`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `inventario_actual` INT NULL DEFAULT '0',
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_compras`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_compras`.`detalle_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compra_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `compra_id` (`compra_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `detalle_compra_ibfk_1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `seguimiento_compras`.`compras` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `detalle_compra_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `seguimiento_compras`.`productos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_compras`.`log_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_compras`.`log_actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(50) NOT NULL,
  `entidad` VARCHAR(50) NOT NULL,
  `entidad_id` INT NULL DEFAULT NULL,
  `descripcion` TEXT NOT NULL,
  `realizado_por` VARCHAR(100) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_fecha` (`fecha_hora` DESC) VISIBLE,
  INDEX `idx_entidad` (`entidad` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_compras`.`recepciones_bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_compras`.`recepciones_bodega` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compra_id` INT NOT NULL,
  `fecha_recibido` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `factura` VARCHAR(100) NULL DEFAULT NULL,
  `contenido` TEXT NULL DEFAULT NULL,
  `cantidad_bultos` INT NULL DEFAULT NULL,
  `quien_recibe` VARCHAR(100) NULL DEFAULT NULL,
  `novedades` TEXT NULL DEFAULT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `compra_id` (`compra_id` ASC) VISIBLE,
  CONSTRAINT `recepciones_bodega_ibfk_1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `seguimiento_compras`.`compras` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguimiento_compras`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguimiento_compras`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `rol` ENUM('GERENTE', 'BODEGA', 'INVENTARIO', 'ADMIN') NOT NULL,
  `activo` TINYINT(1) NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
